import React, { useEffect, useState } from 'react';
import { Award, AlertTriangle, Droplet, Utensils, Activity, Stethoscope, Info } from 'lucide-react';
import { getHealthGoals } from '../api';

const categoryMeta = {
  hydration: { icon: Droplet, color: 'text-blue-600 bg-blue-50' },
  diet: { icon: Utensils, color: 'text-emerald-600 bg-emerald-50' },
  activity: { icon: Activity, color: 'text-amber-600 bg-amber-50' },
  monitoring: { icon: Stethoscope, color: 'text-purple-600 bg-purple-50' },
  general: { icon: Info, color: 'text-slate-600 bg-slate-50' },
};

export default function GoalsComponent({ patientId }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const load = async () => {
      setLoading(true);
      setError('');
      try {
        const result = await getHealthGoals(patientId);
        setData(result);
      } catch (err) {
        setError(err.message || 'Unable to load health goals right now.');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [patientId]);

  if (loading) {
    return (
      <div className="max-w-4xl mx-auto p-6 bg-white rounded-2xl shadow-lg border border-slate-200">
        <p className="text-slate-600">Loading your daily goals...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-4xl mx-auto p-6 bg-white rounded-2xl shadow-lg border border-slate-200">
        <div className="flex items-center gap-3 text-red-700">
          <AlertTriangle className="w-5 h-5" />
          <p>{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="bg-white rounded-2xl shadow-lg border border-slate-200 p-8">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-12 h-12 bg-gradient-to-br from-blue-600 to-cyan-600 rounded-2xl flex items-center justify-center">
            <Award className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="text-3xl font-bold text-slate-900">Daily Health Goals</h2>
            <p className="text-sm text-slate-600">Personalized for {new Date(data.date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</p>
          </div>
        </div>

        <div className="mt-4 inline-flex items-center gap-2 text-xs font-semibold px-3 py-1.5 rounded-full bg-slate-100 text-slate-600">
          {data.source === 'nvidia_nim' ? (
            <>Generated by AI (NVIDIA NIM)</>
          ) : (
            <>Generated from your tracked data (rule-based)</>
          )}
        </div>

        <div className="mt-6 grid gap-4 md:grid-cols-2">
          {data.goals.map((goal, idx) => {
            const meta = categoryMeta[goal.category] || categoryMeta.general;
            const Icon = meta.icon;
            return (
              <div key={idx} className="rounded-2xl border border-slate-200 p-5 bg-slate-50/50">
                <div className="flex items-start gap-3">
                  <div className={`w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 ${meta.color}`}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <div className="flex-1">
                    <p className="text-[11px] font-bold uppercase tracking-widest text-slate-400 mb-1">
                      {goal.category}
                    </p>
                    <p className="font-semibold text-slate-900 leading-snug">{goal.goal}</p>
                    {goal.tip && <p className="text-sm text-slate-600 mt-2">{goal.tip}</p>}
                    {goal.target && (
                      <p className="text-sm font-semibold text-blue-700 mt-2">Target: {goal.target}</p>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {data.disclaimer && (
          <div className="mt-6 p-4 bg-amber-50 border border-amber-200 rounded-xl flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-600 mt-0.5 flex-shrink-0" />
            <p className="text-xs text-amber-800 leading-relaxed">{data.disclaimer}</p>
          </div>
        )}
      </div>
    </div>
  );
}
